sudo: false
language: node_js
node_js:
  - 8
after_success:
  - npm run build
deploy:
  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_DEV -t=$NOW_TOKEN
    on:
      branch: lesson-09
    skip_cleanup: true